### ISSUE TITLE
AD524X with Adafruit RP2040 Feather

### ISSUE THREAD

**Issue by tstahov** [RobTillaart/AD524X#16] opened 2023-01-20 08:41 UTC
Thanks for creating a great library!

I am trying to use the library on an Adafruit RP2040 Feather. 
There are two I2C channels on this board. I initialize the library for the second channel (Wire1) as that is the one the AD5242 is connected to:

AD5242 AD01(0x2C, &Wire1);

The setup code indicates that the AD5242 is found. More specifically, this code:
```cpp
      b = AD01.begin();
      Serial.println(b ? "Begin: true" : "Begin: false");
      Serial.println(AD01.isConnected());
```
produces  this output:
      Begin: true
      1
 
However, when I try to write to the AD5242 there are errors: 
```cpp
      int a = AD01.write(0, 100);
      int b = AD01.write(1, 100 );
      char buff[256];
      sprintf(buff,"Write 1: %d\tWrite 2: %d\n", a, b);
      Serial.println(buff);
```
The output is: 
      Write 1: 4	Write 2: 4
      
From the Arduino documentation for Wire, I believe that a return value of 4 means "other error"
      
I know that the hardware works properly as everything works correctly when I used an ESP32 instead of the RP2040. My board is designed as a feather wing so that I can simply swap feather processors. (For the ESP32 I initialize with AD5242 AD01(0x2C); )  

Any suggestions?

**Comment by RobTillaart** [comment] 2023-01-20 09:00
I have no free RP2040 for testing (need to order some) so first thing I would check is with an I2C scanner if the device can be reached without problems. (apparently the ESP32 can).

e.g. https://github.com/RobTillaart/I2C_SCANNER

**Comment by RobTillaart** [comment] 2023-01-20 09:02
return value of **write()** is return value of **send()** which is indeed the return value of the **Wire.endTransmission()**
```cpp
uint8_t AD524X::write(const uint8_t rdac, const uint8_t value)
{
  if (rdac >= _pmCount) return AD524X_ERROR;

  uint8_t cmd = (rdac == 0) ? AD524X_RDAC0 : AD524X_RDAC1;
  // apply the output lines
  cmd = cmd | _O1 | _O2;
  _lastValue[rdac] = value;
  return send(cmd, value);
}

...

uint8_t AD524X::send(const uint8_t cmd, const uint8_t value)
{
  Wire.beginTransmission(_address);
  Wire.write(cmd);
  Wire.write(value);
  return Wire.endTransmission();
}
```

**Comment by RobTillaart** [comment] 2023-01-20 09:10
```cpp
uint8_t AD524X::write(const uint8_t rdac, const uint8_t value)
```

Note that **write()** needs 2 parameters while your code provides only 1.

Wondering why the ESP32 did work ?


Note for myself, consider adding **write(value)** with default PM == 0 ? (wrapper)

**Comment by RobTillaart** [comment] 2023-01-20 09:17
looking into the library code of Wire of the RP2040 a return value of 4 could indicate 3 causes

```cpp
// Errors:
//  0 : Success
//  1 : Data too long
//  2 : NACK on transmit of address
//  3 : NACK on transmit of data
//  4 : Other error
uint8_t TwoWire::endTransmission(bool stopBit) {
    if (!_running || !_txBegun) {
        return 4;   <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< (A)
    }
    _txBegun = false;
    if (!_buffLen) {
        // Special-case 0-len writes which are used for I2C probing
        return _probe(_addr, _sda, _scl, _clkHz) ? 0 : 2;          <<<<<<<<<<  this is the isConnected() test
    } else {
        auto len = _buffLen;
        auto ret = i2c_write_blocking_until(_i2c, _addr, _buff, _buffLen, !stopBit, make_timeout_time_ms(_timeout));
        _buffLen = 0;
        return (ret == len) ? 0 : 4;   <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< (B)
    }
}
```

You might add a print statement in the library to see which return path is used, A or B

**Comment by tstahov** [comment] 2023-01-20 09:27
You are correct, two arguments are needed. I am using two arguments. 
```cpp
int a = AD01.write(0, 100);
int b = AD01.write(1, 100 );
```
I made a mistake copying code into the webpage. 

(update, I added code block for syntax highlighting as that makes code more readable, use edit post to see how)

**Comment by tstahov** [comment] 2023-01-20 09:39
I had previously tried the Adafruit testbed library and obtained this result: 

Adafruit I2C Scanner
Default port (Wire) I2C scan: 
Secondary port (Wire1) I2C scan: 0x2C,

**Comment by RobTillaart** [comment] 2023-01-20 09:41
> I had previously tried the Adafruit testbed library and obtained this result:
> 
> Adafruit I2C Scanner Default port (Wire) I2C scan: Secondary port (Wire1) I2C scan: 0x2C,

Looks OK so the device can be seen.
think you need to add the prints in the Wire library to see which code path fails.

**Comment by tstahov** [comment] 2023-01-20 09:43
I ran I2C_scanner_simple and the device was not found. Perhaps the scanner is checking only the first I2C port. 

Here is the version information that was printed. 
C:\Users\stahov\Documents\Arduino\libraries\I2C_SCANNER\examples\I2C_scanner_simple\I2C_scanner_simple.ino
I2C_SCANNER_LIB_VERSION: 0.1.3

**Comment by RobTillaart** [comment] 2023-01-20 09:53
> Perhaps the scanner is checking only the first I2C port.

yes, try - I2C_scanner_getWirePortCount.ino

**Comment by tstahov** [comment] 2023-01-20 09:58
Thanks! It's 2:00 am so I will add the prints in the Wire library in the morning.

**Comment by tstahov** [comment] 2023-01-20 20:30
I added print statements in Wire.cpp and found that path B is used

**Comment by RobTillaart** [comment] 2023-01-20 20:48
So not all bytes are sent apparently.
This is a liw level Wire library problem.
The first thing to print now is that timeout variable, as that can be the cause.
Also try to print the number of bytes that are send
Just to get detailed insight where it fails.

**Comment by tstahov** [comment] 2023-01-20 22:33
I suspected the timeout was an issue and tried increasing it, but that didn't fix it. 

I'm trying to use a logic analyzer to debug this. I was able to see signals on the I2C lines when the library first initialized the device, but after this, I see no signals. My guess is that your library is not the problem, but rather this a problem with the core library files for the RP2040. I'll keep you posted.

By the way, thanks for your help with this. I really appreciate it.

**Comment by RobTillaart** [comment] 2023-01-21 08:57
followed the calls goes down to the function **i2c_write_blocking_internal(i2c_inst_t \*i2c, uint8_t addr, const uint8_t \*src, size_t len, bool nostop, check_timeout_fn timeout_check, struct timeout_state \*ts)** that seems to do the work. 

This is a low level function that sends one byte at the time.  checks for timeout after every byte.
Not trivial to analyze but it could help you find where things go wrong. 

----

Other thought
Do you have a different I2C device? if that also fails to work you might have the wrong board selected?
Some boards do not work with the Arduino MBED 2040 See https://github.com/RobTillaart/MCP4725/pull/21

**Comment by tstahov** [comment] 2023-01-21 21:47
I tried both the MBED and Philhower (https://github.com/earlephilhower/arduino-pico) software with the Adafruit RP2040 Feather and had the same issues with both.  

Next, I tried a Pi Pico instead of the Feather. The code runs properly on the Pico but not on the Feather. Thus, either this particular Feather is defective or there is something wrong with the configuration files for the Feather version of the RP2040 board. Given that neither the MBED nor Philhower software worked, I'm guessing the problem is with this particular board. I will order another Feather to confirm. I'll let you know what I find out. 

The conclusion is your library works correctly!

Thanks again for all of the help.

**Comment by RobTillaart** [comment] 2023-01-22 10:35
Maybe the Feather has specific pins for I2C?
Once I had an IC which had swapped to names of two pins on the break out board. 
Took weeks to come up with that idea and minutes to confirm.

Apparently the cause is really outside my library. Although I am interested in the cause, I will not investigate further. 
If you have new insights please post them, as these might be interesting for someone else in the future.

**Comment by RobTillaart** [comment] 2023-01-29 17:01
@tstahov 
As the issue is not caused by the library I close the issue. Feel free to open it again if new insights are made.

**Closed as completed** 2023-01-29 17:03 UTC
Labels: question
